{
	"sources": [
		{
			"path": "../../../../feature.js",
			"eTag": "\"236-zqZ0KKotxCXk65n3bM4jdyBNV6M\""
		}
	],
	"value": {
		"status": "failed",
		"reason": "unexpected-test-throw",
		"detail": {
			"name": "SyntaxError",
			"message": "Identifier 'a' has already been declared",
			"stack": "SyntaxError: Identifier 'a' has already been declared\n    at eval (eval at <anonymous> (eval at fromServer (C:\\Users\\Damien\\Documents\\GitHub\\core\\src\\features\\api.js:683:25)), <anonymous>:1:10)\n    at test$$1.complete (eval at fromServer (C:\\Users\\Damien\\Documents\\GitHub\\core\\src\\features\\api.js:683:25), <anonymous>:187:30)\n    at exec (C:\\Users\\Damien\\Documents\\GitHub\\core\\src\\jsenv.js:2000:39)\n    at C:\\Users\\Damien\\Documents\\GitHub\\core\\src\\jsenv.js:2091:32\n    at Immediate._onImmediate (C:\\Users\\Damien\\Documents\\GitHub\\core\\src\\jsenv.js:1186:37)\n    at processImmediate [as _immediateCallback] (timers.js:396:17)"
		}
	}
}